executor:
  name: nodejs
  options:
    entry: main.ts
inputs_def:
  - handle: s3Client
    json_schema:
      contentMediaType: oomol/var
  - handle: bucket
    json_schema:
      type: string
  - handle: prefix
    json_schema:
      type: string
    value:
    nullable: true
outputs_def:
  - handle: output
    json_schema:
      type: array
      items:
        type: string
title: List by path
icon: ":carbon:list:"
private: true
