executor:
  name: nodejs
  options:
    entry: main.ts
inputs_def:
  - handle: s3Client
    json_schema:
      contentMediaType: oomol/var
  - handle: bucket
    json_schema:
      type: string
  - handle: file
    json_schema:
      type: string
      ui:widget: file
  - handle: key
    json_schema:
      type: string
    nullable: false
outputs_def:
  - handle: output
    json_schema:
      type: string
title: Upload file
icon: ":carbon:upload:"
private: true
