executor:
  name: nodejs
  options:
    entry: main.ts
inputs_def:
  - handle: region
    json_schema:
      type: string
  - handle: accessKey
    json_schema:
      contentMediaType: oomol/secret
      type: string
  - handle: secretAccessKey
    json_schema:
      contentMediaType: oomol/secret
      type: string
  - handle: endpoint
    json_schema:
      type: string
    nullable: true
    value:
outputs_def:
  - handle: client
    json_schema:
      contentMediaType: oomol/var
title: Create s3 client
icon: ":simple-icons:amazons3:"
private: true
